### PR TITLE
added a webcam example

### PR DESCRIPTION
**Pull request by yakir12**

### CODE REVIEW

**Comment by yakir12** [comment]
Sorry, just noticed that CSV was missing as a dependency for the `GermanCredits.jl` demo, so I just pushed that fix here. It doesn't really have anything to do with my webcam demo.

**Comment by hhaensel** [comment]
That's a nice example although it doesn't make use of Quasar so much...
@essenciary I don't have access to StippleDemos, so I cannot merge.

I would want to add some modifications to make it windows compatible (at least for my laptop)
```
const SX = 640
const SY = 360
const FPS = 30
const FMT = Sys.iswindows()  ? "dshow" : "v4l2"
const DEVICE = Sys.iswindows()  ? "video=\"Integrated Webcam\"" : "/dev/video0"
[...]
 io = open(`$exe -hide_banner -loglevel error -f $FMT -r $FPS -s $(SX)x$SY -i $DEVICE -c:v png -vf "crop=in_h:in_h,scale=$(SX)x$SY" -f image2pipe -`)
```

**Comment by yakir12** [comment]
Try it out now. I simplified the ffmpeg pipeline as well. 

Two remaining options are:
1. Adapt it to Quasar. 
2. use VideoIO.jl instead

**Comment by essenciary** [comment]
@hhaensel sent you an invite to join as a maintainer

**Comment by hhaensel** [comment]
> Try it out now. I simplified the ffmpeg pipeline as well.
> 
> Two remaining options are:
> 
> 1. Adapt it to Quasar.

I will spend some thoughts on that, particularly as the PNGFiles issue is solved 😃 
> 2. use VideoIO.jl instead

**Pull request merged**
